/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Main.SolutionShopping;

import TheBusiness.Business.Business;
import TheBusiness.MarketModel.SolutionOffer;
import TheBusiness.MarketModel.SolutionOfferCatalog;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apoorvdhaygude
 */
public class SolutionShoppingCart extends javax.swing.JPanel {

    SolutionOfferCatalog soc;
    Business business;
    JPanel CardSequencePanel;
    SolutionOffer selected;
    SolutionOffer selectedInCart;
    int clicks;

    /**
     * Creates new form SolutionShoppingCart
     */
    public SolutionShoppingCart(Business business, JPanel jp) {
        this.business = business;
        this.soc = this.business.getSolutionOfferCatalog();
        this.CardSequencePanel = jp;
        initComponents();
        refreshSolutionTable();
        clearShoppingCart();
        this.clicks = 0;
    }

    private void refreshSolutionTable() {
        // Clear existing data
        DefaultTableModel model = (DefaultTableModel) solutionTable.getModel();
        model.setRowCount(0);

        // Iterate through the SolutionOfferCatalog and add rows to the table
        for (SolutionOffer so : this.soc.getSolutionoffers()) { // Assuming getSolutionOffers() returns a list of SolutionOffer
            model.addRow(new Object[]{so.getSolutionName(), so.getFloor(), so.getCeiling(), so.getTarget()});
        }
    }

    private void clearShoppingCart() {
        DefaultTableModel model = (DefaultTableModel) cart.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        b_add = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        solutionTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        cart = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        feedback = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        j4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        j9 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productNameTextField = new javax.swing.JTextField();
        Next1 = new javax.swing.JButton();
        b_remove = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setText("X Cancel");
        Back.setName("Back"); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 190, -1));

        b_add.setText("Add");
        b_add.setName("b_add"); // NOI18N
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addActionPerformed(evt);
            }
        });
        add(b_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 190, -1));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        solutionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Floor", "Ceiling", "Target"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        solutionTable.setName("solutionTable"); // NOI18N
        solutionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                solutionTableMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                solutionTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(solutionTable);

        jScrollPane2.setViewportView(jScrollPane1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 620, 170));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Solution Shopping");
        jLabel2.setName("jLabel2"); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 550, -1));

        jLabel8.setText("Solution");
        jLabel8.setName("jLabel8"); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Solution"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cart.setName("cart"); // NOI18N
        cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cartMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cartMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(cart);

        jScrollPane3.setViewportView(jScrollPane4);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 600, 100));

        jLabel9.setText("Shopping Cart");
        jLabel9.setName("jLabel9"); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 280, 20));

        feedback.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Business-wide Product Intelligence", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        feedback.setName("feedback"); // NOI18N
        feedback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Average return on value");
        jLabel6.setName("jLabel6"); // NOI18N
        feedback.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 150, -1));

        j4.setName("j4"); // NOI18N
        feedback.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 150, -1));

        jLabel4.setText("Prices");
        jLabel4.setName("jLabel4"); // NOI18N
        feedback.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 150, -1));

        j9.setName("j9"); // NOI18N
        feedback.add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 150, -1));

        j5.setName("j5"); // NOI18N
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });
        feedback.add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, -1));

        jLabel5.setText("Best Price");
        jLabel5.setName("jLabel5"); // NOI18N
        feedback.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, -1));

        jLabel3.setText("Solution Name");
        jLabel3.setName("jLabel3"); // NOI18N
        feedback.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, -1));

        productNameTextField.setName("productNameTextField"); // NOI18N
        productNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextFieldActionPerformed(evt);
            }
        });
        feedback.add(productNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, -1));

        add(feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 600, 170));
        feedback.getAccessibleContext().setAccessibleName("Solution Intelligence");

        Next1.setText("Submit");
        Next1.setName("Next1"); // NOI18N
        Next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next1ActionPerformed(evt);
            }
        });
        add(Next1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 190, -1));

        b_remove.setText("remove");
        b_remove.setName("b_remove"); // NOI18N
        b_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_removeActionPerformed(evt);
            }
        });
        add(b_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 170, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
//        currentOrder.CancelOrder();
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed

    private void b_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addActionPerformed

        // MARK! TODO!
        // add this.selected (an instance of SolutionOffer) to the shopping cart (this.cart) and let 
        if (selected != null) {
            DefaultTableModel model = (DefaultTableModel) cart.getModel();
            model.addRow(new Object[]{selected}); // Modify this line according to how you want to display the SolutionOffer in the cart
        } else {
            JOptionPane.showMessageDialog(null, "No solution selected", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_b_addActionPerformed

    private void solutionTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solutionTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_solutionTableMouseEntered

    private void solutionTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solutionTableMousePressed
        // TODO add your handling code here:
        int suppliertablesize = solutionTable.getRowCount();
        int selectedrow = solutionTable.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > suppliertablesize - 1) {
            return;
        }
        //this.selected = (SolutionOffer) solutionTable.getValueAt(selectedrow, 0);
        this.clicks ++;
        updateFeedback(this.clicks);

    }//GEN-LAST:event_solutionTableMousePressed

    private void cartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseEntered


    }//GEN-LAST:event_cartMouseEntered

    private void cartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMousePressed
        int suppliertablesize = cart.getRowCount();
        int selectedrow = cart.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > suppliertablesize - 1) {
            return;
        }
        this.selectedInCart = (SolutionOffer) cart.getValueAt(selectedrow, 0);
    }//GEN-LAST:event_cartMousePressed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed

    }//GEN-LAST:event_j5ActionPerformed

    private void productNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextFieldActionPerformed

    }//GEN-LAST:event_productNameTextFieldActionPerformed

    private void Next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next1ActionPerformed
        String message = "You have submitted your order of solutions!";
        JOptionPane.showMessageDialog(null, message, "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_Next1ActionPerformed

    private void b_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_removeActionPerformed
// TODO write this function so when this is called, the this.selectedInCart is deleted and removed from this.cart.
    if (selectedInCart != null) {
        DefaultTableModel model = (DefaultTableModel) cart.getModel();
        model.removeRow(cart.getSelectedRow());
    } else {
        JOptionPane.showMessageDialog(null, "No solution selected in cart", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_b_removeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Next1;
    private javax.swing.JButton b_add;
    private javax.swing.JButton b_remove;
    private javax.swing.JTable cart;
    private javax.swing.JPanel feedback;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JTable solutionTable;
    // End of variables declaration//GEN-END:variables
private void updateFeedback(int clicks) {
        this.selected = this.soc.getSolutionoffers().get(0);
        productNameTextField.setText(selected.getSolutionName());
        String revenues = String.valueOf(selected.getSolutionPrice() + this.clicks);
        j9.setText(revenues);
        j5.setText(String.valueOf(selected.getSolutionPrice() + this.clicks * 10000));
                j4.setText(String.valueOf(selected.getSolutionPrice() + this.clicks * 5000.19));
}
}
